org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT -Djava.net.preferIPv4Stack=true

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
# org.gradle.configuration-cache=false

android.useAndroidX=true
android.enableJetifier=true
android.builtInKotlin=false
android.newDsl=false
